### ISSUE TITLE
cmd-word-manager  should be use main branch?

### ISSUE THREAD

**Issue by heartshare** [plugins-world/LaravelSaas#1]
Problem 1
    - Root composer.json requires fresns/cmd-word-manager dev-master, found fresns/cmd-word-manager[dev-main, v1.0.0, ..., v1.4.1] but it does not match the constraint. Perhaps dev-master was renamed to dev-main?

**Comment by mouyong** [comment]
@heartshare 是否有配置 vcs ？目前我基本上使用的 vcs 完成安装。

如果要使用稳定版本的插件管理器，将 dev-master 改成 dev-main 即可。

一个代码仓库在 gitee: https://gitee.com/fresns/plugin-manager

一个代码仓库在 github: https://github.com/fresns/plugin-manager

**Comment by mouyong** [comment]
https://gitee.com/fresns/cmd-word-manager

这个是命令字管理器的vcs仓库地址。配置一下就可以了。
配置命令：`composer config repositories.cmd-word-manager vcs https://gitee.com/fresns/cmd-word-manager`

![image](https://github.com/plugins-world/LaravelSaas/assets/10336437/ceebd6a8-161d-4529-85c0-9c78013463f6)

**Comment by heartshare** [comment]
composer config repositories.cmd-word-manager vcs https://gitee.com/fresns/cmd-word-manager 可以了.  Thanks
