### ISSUE TITLE
Missing DcatSaas installation in readme 

### ISSUE THREAD

**Issue by heartshare** [plugins-world/LaravelSaas#2]
need to run this: php artisan market:require plugins-world/dcat-saas
before 
php artisan plugin:activate DcatSaas # 启用插件，否则插件不会被加载

**Comment by mouyong** [comment]
是的哦。插件每次更新，都会需要手动启用。因为避免更新后的插件直接导致了程序挂了。

先安装，再启用。

**Comment by mouyong** [comment]
@heartshare  laravel saas 只有对 tenancy 的依赖 和 laravel 官方的 breeze 依赖。没有了 dcatadmin 的依赖。所以和 dcatsaas 不同。它和 dcatsaas 是独立的。在 laravelsaas 中，不用添加 dcatsaas 的安装。
